
import { Navbar } from "@/components/Navbar";
import { Toaster } from "react-hot-toast";



export const metadata = {
  title: "dealer",
  description: "Generated by create next app",
  icons:{
    icon:"/logo.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-light-1"
      >
            <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
